version: "3"

services:
  loki:
    image: grafana/loki:master
    ports:
      - "3100:3100"
      - "9095:9095"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:master
    volumes:
      - /var/log:/var/log
    command: 
      -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki
      
  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    environment:
      GF_EXPLORE_ENABLED: "true"
    networks:
      - loki
      
networks:
  loki:
    driver: bridge