name: Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build src/Serilog.Sinks.Loki.gRPC --configuration Release -o release
    - name: Deploy NuGet Package
      run: dotnet nuget push ./Serilog.Sinks.Loki.gRCP/Serilog.Sinks.Loki.gRCP/src/Serilog.Sinks.Loki.gRPC/release/Serilog.Sinks.Loki.gRPC.1.0.0.nupkg -k "$NUGET_API_KEY" -s https://api.nuget.org/v3/index.json
      
